### ISSUE TITLE
Modrinth App Not Copying YOSBR Config Settings for my Modpack

### ISSUE THREAD

**Issue by Asguho** [shedaniel/your-options-shall-be-respected#16]
I am the maintainer of a modpack that uses YOSBR for the configuration. You can find the modpack on Modrinth: [AsguhoClient Modpack](https://modrinth.com/modpack/asguhoclient)

When I run the modpack from the [prism launcher](https://prismlauncher.org/), it behaves as it is supposed to. However, when I run the modpack from the new [modrinth app](https://modrinth.com/app), it does not copy the settings.

I'm not sure if this issue is related to YOSBR, the Modrinth App, or something on my end. Can someone help me identify the cause of the problem? Thank you!

**Comment by redstonerti** [comment]
I have the same issue.

**Comment by BurningButter** [comment]
@Asguho Did you find a solution to this issue? If you did would you mind posting it here?

**Comment by ItzTK** [comment]
> [@Asguho](https://github.com/Asguho) Did you find a solution to this issue? If you did would you mind posting it here?

Use [Configured Defaults](https://modrinth.com/mod/configured-defaults) instead.
