### ISSUE TITLE
[Feature Request] add option to auto restart/close the game after executing the mod for the first time

### ISSUE THREAD

**Issue by elhertz** [shedaniel/your-options-shall-be-respected#5]
You need to restart the game anyways, so a feature like that would be awesome.

**Comment by shedaniel** [comment]
You need to restart?

**Comment by elhertz** [comment]
When this mod moves config files, they won't work until you restart the game. When I launch the game I'm getting default configs instead the ones I put in "config/yosbr/config".

**Comment by elhertz** [comment]
Nevermind. You can close this issue now.
I forgot I had "DefaultSettings" installed and when I removed it everything started working without restarting.
I'm sorry for wasting your time.
